kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: encryption-key
              secret: hPQif0ix+RQ92zjBbj6+mzinkjjNsYgBeKEEV0lmus8=
      - identity: {}