apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: davidhuang-top-staging
spec:
  secretName: davidhuang-top-staging-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: davidhuang.top
  dnsNames:
  - www.davidhuang.top
  - dev.davidhuang.top
  acme:
    config:
    - http01: 
        ingressClass: nginx
      domains:
        - davidhuang.top
        - www.davidhuang.top
        - dev.davidhuang.top
