apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
 capacity:
   storage: 15Gi
 accessModes:
 - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: local-storage
 local:
   path: /mnt/k8s/local-vol1
 nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - node1.davidhuang.top
         - node2.davidhuang.top

